#!/bin/sh

. ./ca-lib

if [ "$1" != "" ]; then
    NAME=$1
else
    echo "Usage : $0 <NAME>"
    exit 1
fi

CA="root/ca/intermediate"
ROOT=$CA/$NAME

openssl ca -config $CA/openssl.conf -revoke $ROOT/certs/$NAME.cert.pem